# Generated by Django 5.0.2 on 2024-07-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorited',
        ),
    ]
