# Generated by Django 5.0.2 on 2024-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
